### ISSUE TITLE
Unable to sign in using password on "/#/login" page

### ISSUE THREAD

**Issue by kouhei-ioroi** [Timshel/OIDCWarden#10]
In my case, general users use SSO, and organization administrators on OIDCWarden use Email+Password+TOTP.
At some point, logging in by entering a password on the "/#/login" page no longer works.

Only SSO Login is False, but the password text box is not displayed, so it is not possible to enter a password.
(This is also abnormal because the text box was displayed even if Only SSO Login was True.)

![image](https://github.com/user-attachments/assets/0ea43ed5-768b-40a3-aaec-a8f8beeabe42)

![image](https://github.com/user-attachments/assets/7e8b45ac-ae8e-4418-8000-5362fac232f8)

![image](https://github.com/user-attachments/assets/138af989-04d2-494d-b18d-6b8f7c5d8d63)

I also tried removing "SSO_FRONTEND=override", but that made no difference.

By the way, if I try to log in with a password using the Bitwarden Extension, I can login correctly.
Perhaps there's a problem with the WebUI.

Is this a problem only for me?

**Comment by kouhei-ioroi** [comment]
I found the cause.

In "/css/vaultwarden.css", "display: none" is defined for ".master-password-login".

![image](https://github.com/user-attachments/assets/a48c166c-85fd-4ea5-84cb-09a690718868)

As a result, the password input element seems to be hidden.

And I think it's probably here:
https://github.com/Timshel/OIDCWarden/blob/f71f8f5369919df348066218105cdb99e02717a4/src/static/templates/scss/vaultwarden.scss.hbs#L69-L74

But I don't know why it wasn't being judged correctly.

**Comment by Timshel** [comment]
Hey, will check again tomorrow but the password field should be hidden only when `SSO_ONLY=true`.

**Comment by Timshel** [comment]
Just pushed the `v2024.12.1-2` but it should only contain unrelated modifications.

Tried the SSO_ONLY toggle quickly locally and the setting was correctly used.

Just in case I will mention that a `ctrl + F5` is necessary between change to ensure that a cached version is not used.

**Comment by kouhei-ioroi** [comment]
Hello, @Timshel 

I'm a big idiot.
I host it on cloudflare and it was caused by caching and keeping it on the CDN from the origin server.
I purged the origin cache and set the appropriate TTL and it started working fine.

Apologies for the inconvenience.

**Comment by Timshel** [comment]
No worry :)
