### ISSUE TITLE
Zitadel Audience

### ISSUE THREAD

**Issue by Aurel004** [Timshel/OIDCWarden#5]
Hi,

I am trying to add Zitadel to Vaultwarden using your image but I'm facing issues.
In the docs it's written

> Additionally Zitadel include the Project id and the Client Id in the audience of the Id Token. For the validation to work you will need to add the Resource Id as a trusted audience (Client Id is trusted by default). You can control the trusted audience with the config SSO_AUDIENCE_TRUSTED
and

> SSO_AUDIENCE_TRUSTED='^${Project Id}$'

But the thing is that whenever you have multiple apps in the project, they are added in the audience, therefore there is a list in the audience of all the apps Client Id

So, should I add every Client ID in the SSO_AUDIENCE_TRUSTED ? If so, how to add a list ?
The issue with this is that as soon as I add an app, I would need to update the environment variable

Better option (easier for me, not for you) would be to check if the Client ID is present in the list then accept ?

How to deal with this ?

Thank you

**Comment by Timshel** [comment]
Hey,

The `SSO_AUDIENCE_TRUSTED` takes a regex, so you could either: 
 - list all project:  `SSO_AUDIENCE_TRUSTED='^(ProjectId1|ProjectId2|ProjectId3)$'`
 - allow every audience: 
 
Note that this regex applies to "additional audience" the client ID is trusted by default. 
For the issue around adding an app I believe that the audience outside of dev environment are formatted with a radical `id@radical` ? Maybe in this case you can use a regex in the format of `SSO_AUDIENCE_TRUSTED='^.*@radical$'`.

**Comment by Aurel004** [comment]
Hey,

It was like `id@radical` but it is now an unique `id` without `@radical` so I cannot use regex

I guess the only way for me is to allow every audience with `'^*$'`

I am trying to map token's groups to an organization:
group `user` can join vaultwarden org named `myorg` with default collection
group `admin` can join vaultwarden org named `myorg` with default collection plus `administrator` collection. Is it possible ?

I've set:
`SSO_ROLES_ENABLED: true
SSO_ROLES_DEFAULT_TO_USER: false
SSO_ORGANIZATIONS_INVITE: true
SSO_ORGANIZATIONS_ALL_COLLECTIONS: false
SSO_ROLES_TOKEN_PATH: /zitadel:grants:groups:{groupId}
SSO_ORGANIZATIONS_ID_MAPPING: "user:{organizationId};
SSO_ORGANIZATIONS_ALL_COLLECTIONS: false
ORGANIZATION_INVITE_AUTO_ACCEPT: true`

But when I log in, the logs are: `No groups in {email} id_token at /groups
User {email} logged with admin cookie`

Thanks

**Comment by Aurel004** [comment]
Okay thank you I missed this environment variable, I've set it like SSO_ORGANIZATIONS_TOKEN_PATH but now I have an other error:
`[2024-09-30 20:21:25.220][oidcwarden::sso][WARN] Missing organization mapping for admin`
`[2024-09-30 20:21:25.220][oidcwarden::api::identity][INFO] User {email} logged with admin cookie`
`[2024-09-30 20:21:25.221][oidcwarden::sso][DEBUG] Non jwt refresh_token (expiration set to 1730319685)`
`[2024-09-30 20:21:25.222][oidcwarden::api::identity][INFO] User {email} logged in successfully. IP: {IP}`
`[2024-09-30 20:21:25.222][response][INFO] (login) POST /identity/connect/token => 200 OK`
`[2024-09-30 20:21:39.093][request][INFO] POST /api/accounts/verify-password`
`[2024-09-30 20:21:39.239][response][INFO] (verify_password) POST /api/accounts/verify-password => 200 OK`
`[2024-09-30 20:21:39.256][request][INFO] POST /identity/connect/token`
`[2024-09-30 20:21:39.269][reqwest::connect][DEBUG] starting new connection: {zitadel url}`
`[2024-09-30 20:21:39.274][request][INFO] GET /notifications/hub?access_token={token}`
`[2024-09-30 20:21:39.274][oidcwarden::api::notifications][INFO] Accepting Rocket WS connection from {IP}`
`[2024-09-30 20:21:39.274][response][INFO] (websockets_hub) GET /notifications/hub?<data..> => 200 OK`
`[2024-09-30 20:21:39.294][oidcwarden::sso][ERROR] Request to exchange_refresh_token endpoint failed: ServerResponse(StandardErrorResponse { error: unauthorized_client, error_description: Some("grant_type \"refresh_token\" not allowed"), error_uri: None })`
`[2024-09-30 20:21:39.294][oidcwarden::api::identity][ERROR] {"error":"","errorModel":{"message":"Request to exchange_refresh_token endpoint failed: ServerResponse(StandardErrorResponse { error: unauthorized_client, error_description: Some(\"grant_type \\\"refresh_token\\\" not allowed\"), error_uri: None })","object":"error"},"error_description":"","exceptionMessage":null,"exceptionStackTrace":null,"innerExceptionMessage":null,"message":"Request to exchange_refresh_token endpoint failed: ServerResponse(StandardErrorResponse { error: unauthorized_client, error_description: Some(\"grant_type \\\"refresh_token\\\" not allowed\"), error_uri: None })","object":"error","validationErrors":{"":["Request to exchange_refresh_token endpoint failed: ServerResponse(StandardErrorResponse { error: unauthorized_client, error_description: Some(\"grant_type \\\"refresh_token\\\" not allowed\"), error_uri: None })"]}}`
`[2024-09-30 20:21:39.294][response][INFO] (login) POST /identity/connect/token => 401 Unauthorized`
`[2024-09-30 20:21:39.334][tungstenite::protocol][DEBUG] Received close frame: None`
`[2024-09-30 20:21:39.334][tungstenite::protocol][DEBUG] Replying to close with Frame { header: FrameHeader { is_final: true, rsv1: false, rsv2: false, rsv3: false, opcode: Control(Close), mask: None }, payload: [] }`

it happens with these settings:
`SSO_ROLES_ENABLED: true`
`SSO_ROLES_DEFAULT_TO_USER: false`
`SSO_ROLES_TOKEN_PATH: /zitadel:grants:groups:{projectID}`
`SSO_ORGANIZATIONS_INVITE: true`
`SSO_ORGANIZATIONS_TOKEN_PATH: /zitadel:grants:groups:{projectID}`
`SSO_ORGANIZATIONS_ID_MAPPING: "user:{collectionId};admin:{collectionId}"`
`SSO_ORGANIZATIONS_ALL_COLLECTIONS: false`
`ORGANIZATION_INVITE_AUTO_ACCEPT: true`
`SSO_CLIENT_CACHE_EXPIRATION: 600`
zitadel:grants:groups:{projectID} looks like this: `[
    "admin",
    "user"
  ]`

I don't know what's wrong

And I was wondering what this environment variable do ? `SSO_MASTER_PASSWORD_POLICY`

**Comment by Timshel** [comment]
Hum looking at your config first: 
`SSO_ORGANIZATIONS_ID_MAPPING` allow to map to organization so not sure what the `{collectionId}` are supposed to be. The mapping is supposed to be: `"ProviderId:VaultOrganizationId;"`

As for the error message I'm not sure what's happening, it appears that Zitadel is refusing the `grant_type` `exchange_refresh_token` so the app is unable to update the refresh token :(. Can't see much mentioned here: https://zitadel.com/docs/apis/openidoauth/endpoints#refresh-token-grant

**Comment by Aurel004** [comment]
My bad it was `{organizationid}`

I have the same variables set on an other server working with Zitadel too and I can get it to work and login. I don't understand why this is not working on my 1st server, I updated to your last tag but still:

`[2024-10-04 20:56:11.203][oidcwarden::sso][ERROR] Request to exchange_refresh_token endpoint failed: ServerResponse(StandardErrorResponse { error: unauthorized_client, error_description: Some("grant_type \"refresh_token\" not allowed"), error_uri: None })`
`[2024-10-04 20:56:11.203][oidcwarden::api::identity][ERROR] Unable to refresh login credentials: Request to exchange_refresh_token endpoint failed: ServerResponse(StandardErrorResponse { error: unauthorized_client, error_description: Some("grant_type \"refresh_token\" not allowed"), error_uri: None })`
`[2024-10-04 20:56:11.203][response][INFO] (login) POST /identity/connect/token => 401 Unauthorized`
`[2024-10-04 20:56:11.301][tungstenite::protocol][DEBUG] Received close frame: None`

On the working server it says:
`[2024-10-04 20:23:03.843][oidcwarden::sso][DEBUG] No refresh_token present`

What should I try ?

**Comment by Timshel** [comment]
Hum no idea, I would say check your Zitadel configuration to see if there is anything needed for the refresh token grant to be active.
Might check Zitadel logs too maybe there are more details on why:  `grant_type \"refresh_token\" not allowed`

**Comment by Timshel** [comment]
Unless you activated `SSO_AUTH_ONLY_NOT_SESSION` on the other server I see no reason why the server would not call the exchange_refresh_token endpoint.

**Comment by Aurel004** [comment]
I did not activated `SSO_AUTH_ONLY_NOT_SESSION`, they both have the same environment variables set

Anyway as it's fixed, I'm closing it, thank you
