### ISSUE TITLE
"Login failure, existing SSO user with same email" even with SSO_SIGNUPS_MATCH_EMAIL=true

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [Timshel/OIDCWarden#7]
Hi,

I have the following config:
```yaml
      - DOMAIN=https://vault.${DOMAIN}
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false

      - SSO_ENABLED=true
      - SSO_PKCE=true
      - SSO_ONLY=true
      - SSO_AUTHORITY=https://api.auth.${DOMAIN}

      - SSO_AUDIENCE_TRUSTED=REDACTED
      - SSO_CLIENT_ID=REDACTED
      - SSO_CLIENT_SECRET=dummy
      - SSO_SCOPES=email profile offline_access

      - SSO_FRONTEND=override
      - SSO_ROLES_ENABLED=true
      - SSO_ROLES_TOKEN_PATH=/my:zitadel:grants
      - SSO_SIGNUPS_MATCH_EMAIL=true

      - EXPERIMENTAL_CLIENT_FEATURE_FLAGS=fido2-vault-credentials,autofill-overlay,autofill-v2,browser-fileless-import
      - SENDS_ALLOWED=false
```

Login works fine.
I tried the following:
1. Creating a new user in my SSO solution
2. Login to OIDCWarden, set up new account (Master password)
3. Delete user in my SSO solutioon
4. Recreate user with same email in my SSO solution
5. Try to login to OIDCWarden

If I understood correctly, with SSO_SIGNUPS_MATCH_EMAIL=true, OIDCWarden should re-link this new user to its existing user with the same email. But I get the following error:
`Login failure (https://api.auth.REDACTED/REDACTED), existing SSO user (REDACTED) with same email (REDACTED)`

Did I misunderstood SSO_SIGNUPS_MATCH_EMAIL ?
If not, is that a bug ? Did I do something wrong ?

Thanks in advance for your help, have a nice day

**Comment by Timshel** [comment]
Hey,

I'm guessing you are testing locally, and you wiped your SSO provider once ?

The error means that a different SSO user than the one trying to log is associated with the user (More details: [SSO.md#account-and-email-handling](https://github.com/Timshel/OIDCWarden/blob/main/SSO.md#account-and-email-handling)).
The `SSO_SIGNUPS_MATCH_EMAIL` allow making the association but only if the account is not already associated with another SSO user.

If you are testing locally the simplest is to wipe the DB.
If not there is two potential case :
- You have recently modified your SSO provider (new url or new users), so the error is expected. 
  You will need to ```TRUNCATE TABLE sso_users;```, this will remove all associations and on the next login the association will then be possible (this has no impact on the user data).
 - You made no change to your provider; in this case it might indicate that the `identifier` returned by your provider is not stable and would probably be a bug.

**Comment by LeVraiRoiDHyrule** [comment]
Thanks for your answer.

I didn't change the SSO provider or its URL, I have done nothing more than what I have described above.
Is this behaviour normal with what I am doing ?

I have deleted the user in the SSO provider but it still exists in OIDC warden, so it could be that an association is still done in OIDC Warden and then it refuses because the SSO user trying to log in with same email is a different user from OIDCwarden. There could be a link left in the DB.
But isn't `SSO_SIGNUPS_MATCH_EMAIL` supposed to link it again with the new user with same email even if it is technically different ?
The user may be already associated in OIDCWarden but then I don't understand the point of `SSO_SIGNUPS_MATCH_EMAIL` if I have edit the DB manually.

**Comment by Timshel** [comment]
The `SSO_SIGNUPS_MATCH_EMAIL` allow associating an account with no SSO user with a new SSO user based on the email.

If you have deleted the user after having already associated then yes the association is still present in the DB.

Overwriting the SSO user is not supported (this is similar to an account takeover) so you will need to manually delete the association in db.
