### ISSUE TITLE
When click the SSO button with "/#/login", an authentication error occurs if the organization name contains double-byte characters. (also Extensions)

### ISSUE THREAD

**Issue by kouhei-ioroi** [Timshel/OIDCWarden#9]
Hi.

I've been using Vaultwarden for a long time.

I found your SSO feature very attractive, so I decided to move to OIDCWarden.

I tried to load the previous data as it is and authenticate with Azure EntraID, but I encountered the following problem.
```
{
    "error": "",
    "errorModel": {
        "message": "Failed to retrive redirect_uri with UDqucBTViLcaykEOqX9aJV893mnW67q554NSmspSpFaVwtOKkOQiRPHEXTMt3LyO:clientId=browser_identifier=%u3075%u3041%u307f%u308a%u30fc",
        "object": "error"
    },
    "error_description": "",
    "exceptionMessage": null,
    "exceptionStackTrace": null,
    "innerExceptionMessage": null,
    "message": "Failed to retrive redirect_uri with UDqucBTViLcaykEOqX9aJV893mnW67q554NSmspSpFaVwtOKkOQiRPHEXTMt3LyO:clientId=browser_identifier=%u3075%u3041%u307f%u308a%u30fc",
    "object": "error",
    "validationErrors": {
        "": [
            "Failed to retrive redirect_uri with UDqucBTViLcaykEOqX9aJV893mnW67q554NSmspSpFaVwtOKkOQiRPHEXTMt3LyO:clientId=browser_identifier=%u3075%u3041%u307f%u308a%u30fc"
        ]
    }
}
```
The above error log is the result when the organization name is `ふぁみりー`.

After several tries, I found that an error occurs when all of the following conditions are met:

- SSO is performed by an extension
- The organization name contains double-byte characters

This does not occur with normal browser SSO, but only with the Bitwarden extension.

Changing the organization name to one that does not contain double-byte characters is not a problem for me, but I feel it would be more convenient if this was improved.

Sorry for my poor English. Thanks.

> Server: OIDCWarden 2024.8.3(Docker alpine)
> Client: Windows 11 24H2 Japanese with Microsoft Edge 131.0.2903.70
> Bitwarden Extension: 2024.11.2

**Comment by kouhei-ioroi** [comment]
@Timshel 
Thank you for your reply.

![image](https://github.com/user-attachments/assets/3861351d-5b11-4c4c-9ecd-f551c6158f29)

Ah, I was so stupid. In the admin menu, the version is v2024.10.2-3, so it's definitely the latest version (I was reading the numbers on the OIDCWarden homepage).

Just to be sure, I tried both the alpine tag and the latest-alpine tag, but since the versions are the same, there was no difference in behavior.
And it's certain that only the extension's SSO fails.

My organization enforces "Account recovery administration", "Single organization", and "Remove individual vault". Could these be affecting me?

![image](https://github.com/user-attachments/assets/9d50234f-8574-4740-bfe9-247eeb237cf3)

**Comment by Timshel** [comment]
> Ah, I was so stupid.

You were not just realized I messed up the docker releases :(.

 Ok, I think I understand where the issue is, I have yet to reproduce it but I should be able to.

**Comment by kouhei-ioroi** [comment]
Hello, @Timshel 

As a test, we disabled all of these policies and then added the user back to the organization, but it didn't work.

We also confirmed that an error occurs when joining multiple organizations rather than a single one, and one of the organizations contains double-byte characters in its name.

This is the error message that appears when a user who has joined an organization named "testテスト試験" and an organization named "family" attempts SSO with the extension.

```
{
    "error": "",
    "errorModel": {
        "message": "Failed to retrive redirect_uri with WvgfSXgBGmyq4d6L5GV6dbfmjI9Td0HCGauFDc6v52e4hA2pVXZhq42C3ZU2Wypy:clientId=browser_identifier=test%u30c6%u30b9%u30c8%u8a66%u9a13",
        "object": "error"
    },
    "error_description": "",
    "exceptionMessage": null,
    "exceptionStackTrace": null,
    "innerExceptionMessage": null,
    "message": "Failed to retrive redirect_uri with WvgfSXgBGmyq4d6L5GV6dbfmjI9Td0HCGauFDc6v52e4hA2pVXZhq42C3ZU2Wypy:clientId=browser_identifier=test%u30c6%u30b9%u30c8%u8a66%u9a13",
    "object": "error",
    "validationErrors": {
        "": [
            "Failed to retrive redirect_uri with WvgfSXgBGmyq4d6L5GV6dbfmjI9Td0HCGauFDc6v52e4hA2pVXZhq42C3ZU2Wypy:clientId=browser_identifier=test%u30c6%u30b9%u30c8%u8a66%u9a13"
        ]
    }
}
```

I know that when I change the organization name, the `test%u30c6%u30b9%u30c8%u8a66%u9a13` part in the log changes dynamically to match the organization name.

I'm sure that the name of the organization the user is a member of is being passed here. 
(But why does the error log only show the name of one organization?)

I don't know why it only fails with the extension.

I also tried it with the mobile app (Android 2024.10.0(11270)) and was able to SSO without any problems.

**Comment by kouhei-ioroi** [comment]
I'm not sure if this is correct, but it seems that the last organization joined is passed in as information at the time of SSO.

When I changed the name of the new organization to something like "org_example" and the previous organization to a name that included double-byte characters, there were no problems with authentication.

and When I then deleted the new organization and joined only the previous organization, the same error occurred. If I changed the organization name so that it does not contain double-byte characters, SSO was successful.

I suspect there may be some issue with the SSO Identifier or something related to that.

**Comment by Timshel** [comment]
Hey 

Sorry I could have given you more information, what I believe is happening is that the default Bitwarden client check if an organization is associated with the user email (I return the organization name if it's the case), this is used in two ways:

- to prefill a page where the organization Id is asked (In the OIDC web client the field is hidden and a default value is used).
- As part of the `state` which is passed around the sso flow. 

Somewhere the encoding/decoding of the `state` is done incorrectly not sure where at the moment.

As a workaround when using the extension you can input a random email, it will not be associated with any organization so a dummy value will be returned. The identity will still be correct it only use information returned by the SSO.

**Comment by kouhei-ioroi** [comment]
Hello, @Timshel 

Thanks for the detailed insight!

I got the same error when I entered my email address in the browser with the default "/#/login" and then clicked SSO.

So I think it's not just the extension, but the problem is with encoding/decoding the organization information as you pointed out.

For now,

- Add `SSO_FRONTEND=override`
- In the case of the extension, enter a random address when logging in and then click the SSO button

This should solve the problem tentatively.

I hope that the causes of these issues can be identified and resolved.
I will contact you if I notice anything. Thank you.

**Comment by kouhei-ioroi** [comment]
Hello, @Timshel 

When I checked the network log as you pointed out, I found that the "state" had changed.
This is the result of `/identity/connect/authorize`.
![image](https://github.com/user-attachments/assets/b618f605-91e9-4ac1-9b55-e18ceb20a5bd)
encoded:`_identifier=家族` -> decoded:`_identifier=%E5%AE%B6%E6%97%8F`

And here are the results from EntraID, "=" is also encoded, but this probably doesn't matter.
![image](https://github.com/user-attachments/assets/043bc52f-437e-468d-baa7-be97350e8bb5)
encoded:`_identifier=家族` -> decoded:`_identifier%3D%E5%AE%B6%E6%97%8F`

But `/identity/connect/oidc-signin` has a different "state"!
![image](https://github.com/user-attachments/assets/5c75679b-f215-4262-a3c0-2b786681cbf3)
encoded:`_identifier=%u5bb6%u65cf` -> decoded:`_identifier%3d%25u5bb6%25u65cf`

I'm pretty sure it's probably a Unicode escape sequence.

**Comment by Timshel** [comment]
Ok, 
So this look most likely an issue with Entra, unless some Content-Encoding is ignored.
I think I will test encoding the state to base64 before sending it to the provider to prevent such issue.

**Comment by kouhei-ioroi** [comment]
Hello, @Timshel 
I don't have a problem with not being able to use double-byte characters in the organization name, so I'll continue using it as is.
I'm glad you found the cause. Thank you for your help.

# For those who are suffering the same pain
Currently, when using the combination of OIDCWarden and EntraID, the organization name is encoded with a Unicode escape sequence, which can cause SSO to fail.

To avoid these issues, consider one of the following three options:

- Use an IdP other than EntraID
- Do not include double-byte characters in the organization name
- Add `SSO_FRONTEND=override` and enter a random email address when signing in to the extension, then click the SSO button

**Comment by kouhei-ioroi** [comment]
Hello, @Timshel 

Wow, what an insane feat!

Yes, I can SSO successfully using all methods.

It looks like state is now passing `_identifier=Vaultwarden`.
> `/identity/connect/authorize`
> ![image](https://github.com/user-attachments/assets/a92ecab2-a65b-4e28-9198-c57617c4db81)

> `EntraID`
> ![image](https://github.com/user-attachments/assets/63ca20ec-5076-49f3-adb3-4a80d289d3d8)

> `/identity/connect/oidc-signin`
> ![image](https://github.com/user-attachments/assets/0232a640-4442-49e6-9ac0-118331014e9e)

> `/sso-connector.html`
> ![image](https://github.com/user-attachments/assets/8b64dc41-1747-4909-9bd1-be29f21822f4)

I'm concerned that there are two patterns of "state", but I think it's working properly anyway.

My sincerest thanks to you!

**Comment by Timshel** [comment]
The second pattern of `state` is the base64 version which is sent to the provider :).

**Comment by kouhei-ioroi** [comment]
Hello, @Timshel 

Ah, I see! You were encoding and decoding the entire "state" in base64.

Indeed, when I base64 decoded the "state" of `EntraID` and `/identity/connect/oidc-signin`, I got the same result.
These problems would have been completely solved, Thank you so much!
